version: "3.8"

networks :
    laravel:
services:

    nginx:
        networks:
            - laravel
        image: nginx:stable-alpine
        container_name: nginx_for_laravel
        ports:
            -   "8081:80"
        volumes:
            -   "./:/var/www/html"
            - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - mysql
    mysql:
        networks:
            - laravel

        image: mysql:8
        container_name: mysql_for_laravel
        ports:
            -   "3337:3336"
        volumes:
            -   "./mysql:/var/lib/mysql"
        restart: unless-stopped
        tty: true
        environment:
            - DB_DATABASE=laravel-vue-graphql-notes
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
            - SERVICE_TAG=dev
            - SERVICE_NAME=mysql
            - MYSQL_ALLOW_EMPTY_PASSWORD=true

    php:
        networks:
            - laravel
        build:
            context: .
            dockerfile: DockerFile
        container_name: php_for_laravel
        ports:
            -   "9000:9000"
        volumes:
            -   "./:/var/www/html"
    phpmyadmin:
        networks:
            - laravel
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        container_name: pma_for_laravel
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8082:80"
#    node:
#        networks:
#            - laravel
#        command: npm run dev
#        build:
#            context: .
#            dockerfile: DockerFile-node
#        ports:
#            - "3001:3000"
#        volumes:
#            - ./:/app

